theme: "lreed"
paginate: 10
baseURL: "https://lreed.net/"
languageCode: "en"
title: "Luke Reed"
publishdir: "public"
googleAnalytics: "UA-41029335-5"
summaryLength: 30
markup:
  highlight:
    codeFences: true
    lineNos: true
    lineNumbersInTable: true
    style: "dracula"
params:
  author: "Luke Reed"
  description: "Site Reliability Engineer"
  copyright: "Copyright Luke Reed 2018-2023. All rights reserved."
  social:
    github: "lucasreed"
    linkedin: "luke-reed-0125"
  # style:
  #   primaryColor: "orangered"
